version: '3.9'

services: 
  postgres:
    image: postgres:18.0-alpine3.22
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot
      PGDATA: /data/pgdata
    ports:
      - "5432:5432"
    volumes: 
      - ./pgdata:/data/pgdata

# volumes:
#   pgdata:
#     driver: local